version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8008
    volumes:
      - '.:/app'
    ports:
      - '8008:8008'
    environment:
      - DATABASE_URL=postgresql://myuser:secret@db:5432/rides_db
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine
    container_name: postgres_container_transport
    volumes:
      - postgres_data_transport:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=rides_db
    expose: 
      - '5432'

volumes:
  postgres_data_transport:









# version: '3.11'
# services:
#   db:
#     image: 'postgres:latest'
#     container_name: postgres_container_transport
#     restart: always
#   environment:
#     - POSTGRES_USER=myuser
#     - POSTGRES_PASSWORD=secret
#     - POSTGRES_DB=rides_db
#   ports:
#     - '5432:5432'
#   volumes:
#     - './data:/var/lib/postgresql/data'
#   app:
#     build: .
#     ports:
#       - '8008:8008'
#     depends_on:
#       - db
#     volumes:
#       - '.:/app'
#     command: >-
#       uvicorn src.app.main:app --reload --workers 1 --host 0.0.0.0 --port 8008
#       --env-file .env
